name: Erlang CI

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Erlang
              uses: erlef/setup-beam@v1
              with:
                  otp-version: 24

            - name: Setup rebar3
              run: |
                  sudo apt-get update
                  sudo apt-get -y install rebar3

            - name: Run Dialyzer
              run: |
                  rebar3 dialyzer

            - name: Compile
              run: |
                  rebar3 escriptize

            - name: Run with Input
              run: | 
                  # Передача значений в lab3 через стандартный ввод
                  echo -e "0 0\n1.571 1\n3.142 0\n4.712 -1\n12.568 0\nstop" | ./_build/default/bin/lab3 --algorithms=lagrange,linear --frequency=1
